export const tasks = [
  { id: "0", name: "Your first task for today", desc: "chuj ci w dupe" },
  { id: "1", name: "Walk the dog", desc: "chuj ci w dupe" },
  { id: "2", name: "Make boilerplate for new project", desc: "chuj ci w dupe" },
  { id: "3", name: "Make groceries list", desc: "chuj ci w dupe" },
  { id: "4", name: "Do something else", desc: "chuj ci w dupe" },
  { id: "5", name: "Your first task for today", desc: "chuj ci w dupe" },
  { id: "6", name: "Walk the dog", desc: "chuj ci w dupe" },
  { id: "7", name: "Make boilerplate for new project", desc: "chuj ci w dupe" },
  { id: "8", name: "Make groceries list", desc: "chuj ci w dupe" },
  { id: "9", name: "Do something else", desc: "chuj ci w dupe" },
  { id: "10", name: "Walk the dog", desc: "chuj ci w dupe" },
  { id: "11", name: "Make boilerplate for new project", desc: "chuj ci w dupe" },
  { id: "12", name: "Make groceries list", desc: "chuj ci w dupe" },
  { id: "13", name: "Do something else", desc: "chuj ci w dupe" },
];
